# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
GSi <- function(U, V) {
    .Call('_rpm_GSi', PACKAGE = 'rpm', U, V)
}

#' @export
PSeqcond <- function(beta, Gamma, S, X, Z, pmfW, pmfM, gw, gm) {
    .Call('_rpm_PSeqcond', PACKAGE = 'rpm', beta, Gamma, S, X, Z, pmfW, pmfM, gw, gm)
}

#' @export
PSgeqcond <- function(beta, Gamma, S, X, Z, pmfW, pmfM, gw, gm) {
    .Call('_rpm_PSgeqcond', PACKAGE = 'rpm', beta, Gamma, S, X, Z, pmfW, pmfM, gw, gm)
}

PropMax <- function(stat) {
    .Call('_rpm_PropMax', PACKAGE = 'rpm', stat)
}

#' @export
augpmf <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, gw, gm) {
    .Call('_rpm_augpmf', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, gw, gm)
}

#' @export
augpmfWM <- function(pmfW, pmfM, pmf, gw, gm, pmfW_N, pmfM_N, gwN, gmN) {
    .Call('_rpm_augpmfWM', PACKAGE = 'rpm', pmfW, pmfM, pmf, gw, gm, pmfW_N, pmfM_N, gwN, gmN)
}

#' @export
augpmfnew <- function(beta, GammaW, GammaM, S, X, Z, pmfW, pmfM, gw, gm) {
    .Call('_rpm_augpmfnew', PACKAGE = 'rpm', beta, GammaW, GammaM, S, X, Z, pmfW, pmfM, gw, gm)
}

#' @export
checkstable <- function(U, V, m, w) {
    .Call('_rpm_checkstable', PACKAGE = 'rpm', U, V, m, w)
}

colMax <- function(stat) {
    .Call('_rpm_colMax', PACKAGE = 'rpm', stat)
}

#' @export
eqcond <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints) {
    .Call('_rpm_eqcond', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints)
}

#' @export
geqcond <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints) {
    .Call('_rpm_geqcond', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints)
}

#' @export
gloglik <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints) {
    .Call('_rpm_gloglik', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints)
}

#' @export
hloglik <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints) {
    .Call('_rpm_hloglik', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints)
}

#' @export
loglik <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints) {
    .Call('_rpm_loglik', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm, constraints)
}

#' @export
probcounts <- function(beta, Gamma, S, X, Z, pmfW, pmfM, counts, gw, gm) {
    .Call('_rpm_probcounts', PACKAGE = 'rpm', beta, Gamma, S, X, Z, pmfW, pmfM, counts, gw, gm)
}

#' @export
qloglik <- function(beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm) {
    .Call('_rpm_qloglik', PACKAGE = 'rpm', beta, GammaW, GammaM, Sd, Xd, Zd, Sdim, Xdim, Zdim, pmfW, pmfM, pmf, counts, gw, gm)
}

rowMax <- function(stat) {
    .Call('_rpm_rowMax', PACKAGE = 'rpm', stat)
}

rowwise_imax_idx <- function(A) {
    .Call('_rpm_rowwise_imax_idx', PACKAGE = 'rpm', A)
}

rowwise_max_idx <- function(A) {
    .Call('_rpm_rowwise_max_idx', PACKAGE = 'rpm', A)
}

#' @export
stablearma <- function(U, V, m, w) {
    .Call('_rpm_stablearma', PACKAGE = 'rpm', U, V, m, w)
}

